# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/FPGAProject/01102022/FPGAResearch/5_Final_Submission/Simulink/IP_Core_Based/TN_16bit/vivado/sysgen_STN/sysgen_STN.srcs/sources_1/ip/stn_16bit_0/stn_16bit_0.xci
# IP: The module: 'stn_16bit_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/FPGAProject/01102022/FPGAResearch/5_Final_Submission/Simulink/IP_Core_Based/TN_16bit/vivado/sysgen_STN/sysgen_STN.gen/sources_1/ip/stn_16bit_0/stn_16bit_c_addsub_v12_0_i0/stn_16bit_c_addsub_v12_0_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==stn_16bit_c_addsub_v12_0_i0 || ORIG_REF_NAME==stn_16bit_c_addsub_v12_0_i0} -quiet] -quiet

# IP: e:/FPGAProject/01102022/FPGAResearch/5_Final_Submission/Simulink/IP_Core_Based/TN_16bit/vivado/sysgen_STN/sysgen_STN.gen/sources_1/ip/stn_16bit_0/stn_16bit_c_addsub_v12_0_i1/stn_16bit_c_addsub_v12_0_i1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==stn_16bit_c_addsub_v12_0_i1 || ORIG_REF_NAME==stn_16bit_c_addsub_v12_0_i1} -quiet] -quiet

# IP: e:/FPGAProject/01102022/FPGAResearch/5_Final_Submission/Simulink/IP_Core_Based/TN_16bit/vivado/sysgen_STN/sysgen_STN.gen/sources_1/ip/stn_16bit_0/stn_16bit_cordic_v6_0_i0/stn_16bit_cordic_v6_0_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==stn_16bit_cordic_v6_0_i0 || ORIG_REF_NAME==stn_16bit_cordic_v6_0_i0} -quiet] -quiet

# IP: e:/FPGAProject/01102022/FPGAResearch/5_Final_Submission/Simulink/IP_Core_Based/TN_16bit/vivado/sysgen_STN/sysgen_STN.gen/sources_1/ip/stn_16bit_0/stn_16bit_mult_gen_v12_0_i0/stn_16bit_mult_gen_v12_0_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==stn_16bit_mult_gen_v12_0_i0 || ORIG_REF_NAME==stn_16bit_mult_gen_v12_0_i0} -quiet] -quiet

# XDC: e:/FPGAProject/01102022/FPGAResearch/5_Final_Submission/Simulink/IP_Core_Based/TN_16bit/vivado/sysgen_STN/sysgen_STN.gen/sources_1/ip/stn_16bit_0/constrs/stn_16bit.xdc
# XDC: The top module name and the constraint reference have the same name: 'stn_16bit_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: e:/FPGAProject/01102022/FPGAResearch/5_Final_Submission/Simulink/IP_Core_Based/TN_16bit/vivado/sysgen_STN/sysgen_STN.srcs/sources_1/ip/stn_16bit_0/stn_16bit_0.xci
# IP: The module: 'stn_16bit_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/FPGAProject/01102022/FPGAResearch/5_Final_Submission/Simulink/IP_Core_Based/TN_16bit/vivado/sysgen_STN/sysgen_STN.gen/sources_1/ip/stn_16bit_0/stn_16bit_c_addsub_v12_0_i0/stn_16bit_c_addsub_v12_0_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==stn_16bit_c_addsub_v12_0_i0 || ORIG_REF_NAME==stn_16bit_c_addsub_v12_0_i0} -quiet] -quiet

# IP: e:/FPGAProject/01102022/FPGAResearch/5_Final_Submission/Simulink/IP_Core_Based/TN_16bit/vivado/sysgen_STN/sysgen_STN.gen/sources_1/ip/stn_16bit_0/stn_16bit_c_addsub_v12_0_i1/stn_16bit_c_addsub_v12_0_i1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==stn_16bit_c_addsub_v12_0_i1 || ORIG_REF_NAME==stn_16bit_c_addsub_v12_0_i1} -quiet] -quiet

# IP: e:/FPGAProject/01102022/FPGAResearch/5_Final_Submission/Simulink/IP_Core_Based/TN_16bit/vivado/sysgen_STN/sysgen_STN.gen/sources_1/ip/stn_16bit_0/stn_16bit_cordic_v6_0_i0/stn_16bit_cordic_v6_0_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==stn_16bit_cordic_v6_0_i0 || ORIG_REF_NAME==stn_16bit_cordic_v6_0_i0} -quiet] -quiet

# IP: e:/FPGAProject/01102022/FPGAResearch/5_Final_Submission/Simulink/IP_Core_Based/TN_16bit/vivado/sysgen_STN/sysgen_STN.gen/sources_1/ip/stn_16bit_0/stn_16bit_mult_gen_v12_0_i0/stn_16bit_mult_gen_v12_0_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==stn_16bit_mult_gen_v12_0_i0 || ORIG_REF_NAME==stn_16bit_mult_gen_v12_0_i0} -quiet] -quiet

# XDC: e:/FPGAProject/01102022/FPGAResearch/5_Final_Submission/Simulink/IP_Core_Based/TN_16bit/vivado/sysgen_STN/sysgen_STN.gen/sources_1/ip/stn_16bit_0/constrs/stn_16bit.xdc
# XDC: The top module name and the constraint reference have the same name: 'stn_16bit_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
