# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/config.xdc

# IP: ip/bram_stn_64bit_0_1/bram_stn_64bit_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bram_stn_64bit_0 || ORIG_REF_NAME==bram_stn_64bit_0} -quiet] -quiet
