# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/FPGAProject/01102022/FPGAResearch/6_FinalExam/Vivado/SumofTwoNeuron_64bit/vivado/sysgen_STN/sysgen_STN.srcs/sources_1/ip/fourto4genip_0/fourto4genip_0.xci
# IP: The module: 'fourto4genip_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGAProject/01102022/FPGAResearch/6_FinalExam/Vivado/SumofTwoNeuron_64bit/vivado/sysgen_STN/sysgen_STN.gen/sources_1/ip/fourto4genip_0/constrs/fourto4genip.xdc
# XDC: The top module name and the constraint reference have the same name: 'fourto4genip_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: e:/FPGAProject/01102022/FPGAResearch/6_FinalExam/Vivado/SumofTwoNeuron_64bit/vivado/sysgen_STN/sysgen_STN.srcs/sources_1/ip/fourto4genip_0/fourto4genip_0.xci
# IP: The module: 'fourto4genip_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGAProject/01102022/FPGAResearch/6_FinalExam/Vivado/SumofTwoNeuron_64bit/vivado/sysgen_STN/sysgen_STN.gen/sources_1/ip/fourto4genip_0/constrs/fourto4genip.xdc
# XDC: The top module name and the constraint reference have the same name: 'fourto4genip_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
