# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/FPGAProject/01102022/FPGAResearch/5_Final_Submission/Simulink/BRAM_LT_Based/BRAM32bit/vivado/sysgen_STN/sysgen_STN.srcs/sources_1/ip/bram_stn_32bit_0/bram_stn_32bit_0.xci
# IP: The module: 'bram_stn_32bit_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/FPGAProject/01102022/FPGAResearch/5_Final_Submission/Simulink/BRAM_LT_Based/BRAM32bit/vivado/sysgen_STN/sysgen_STN.gen/sources_1/ip/bram_stn_32bit_0/bram_stn_32bit_c_addsub_v12_0_i0/bram_stn_32bit_c_addsub_v12_0_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bram_stn_32bit_c_addsub_v12_0_i0 || ORIG_REF_NAME==bram_stn_32bit_c_addsub_v12_0_i0} -quiet] -quiet

# IP: e:/FPGAProject/01102022/FPGAResearch/5_Final_Submission/Simulink/BRAM_LT_Based/BRAM32bit/vivado/sysgen_STN/sysgen_STN.gen/sources_1/ip/bram_stn_32bit_0/bram_stn_32bit_c_addsub_v12_0_i1/bram_stn_32bit_c_addsub_v12_0_i1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bram_stn_32bit_c_addsub_v12_0_i1 || ORIG_REF_NAME==bram_stn_32bit_c_addsub_v12_0_i1} -quiet] -quiet

# IP: e:/FPGAProject/01102022/FPGAResearch/5_Final_Submission/Simulink/BRAM_LT_Based/BRAM32bit/vivado/sysgen_STN/sysgen_STN.gen/sources_1/ip/bram_stn_32bit_0/bram_stn_32bit_div_gen_v5_1_i0/bram_stn_32bit_div_gen_v5_1_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bram_stn_32bit_div_gen_v5_1_i0 || ORIG_REF_NAME==bram_stn_32bit_div_gen_v5_1_i0} -quiet] -quiet

# IP: e:/FPGAProject/01102022/FPGAResearch/5_Final_Submission/Simulink/BRAM_LT_Based/BRAM32bit/vivado/sysgen_STN/sysgen_STN.gen/sources_1/ip/bram_stn_32bit_0/bram_stn_32bit_mult_gen_v12_0_i0/bram_stn_32bit_mult_gen_v12_0_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bram_stn_32bit_mult_gen_v12_0_i0 || ORIG_REF_NAME==bram_stn_32bit_mult_gen_v12_0_i0} -quiet] -quiet

# XDC: e:/FPGAProject/01102022/FPGAResearch/5_Final_Submission/Simulink/BRAM_LT_Based/BRAM32bit/vivado/sysgen_STN/sysgen_STN.gen/sources_1/ip/bram_stn_32bit_0/constrs/bram_stn_32bit.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_stn_32bit_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: e:/FPGAProject/01102022/FPGAResearch/5_Final_Submission/Simulink/BRAM_LT_Based/BRAM32bit/vivado/sysgen_STN/sysgen_STN.srcs/sources_1/ip/bram_stn_32bit_0/bram_stn_32bit_0.xci
# IP: The module: 'bram_stn_32bit_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/FPGAProject/01102022/FPGAResearch/5_Final_Submission/Simulink/BRAM_LT_Based/BRAM32bit/vivado/sysgen_STN/sysgen_STN.gen/sources_1/ip/bram_stn_32bit_0/bram_stn_32bit_c_addsub_v12_0_i0/bram_stn_32bit_c_addsub_v12_0_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bram_stn_32bit_c_addsub_v12_0_i0 || ORIG_REF_NAME==bram_stn_32bit_c_addsub_v12_0_i0} -quiet] -quiet

# IP: e:/FPGAProject/01102022/FPGAResearch/5_Final_Submission/Simulink/BRAM_LT_Based/BRAM32bit/vivado/sysgen_STN/sysgen_STN.gen/sources_1/ip/bram_stn_32bit_0/bram_stn_32bit_c_addsub_v12_0_i1/bram_stn_32bit_c_addsub_v12_0_i1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bram_stn_32bit_c_addsub_v12_0_i1 || ORIG_REF_NAME==bram_stn_32bit_c_addsub_v12_0_i1} -quiet] -quiet

# IP: e:/FPGAProject/01102022/FPGAResearch/5_Final_Submission/Simulink/BRAM_LT_Based/BRAM32bit/vivado/sysgen_STN/sysgen_STN.gen/sources_1/ip/bram_stn_32bit_0/bram_stn_32bit_div_gen_v5_1_i0/bram_stn_32bit_div_gen_v5_1_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bram_stn_32bit_div_gen_v5_1_i0 || ORIG_REF_NAME==bram_stn_32bit_div_gen_v5_1_i0} -quiet] -quiet

# IP: e:/FPGAProject/01102022/FPGAResearch/5_Final_Submission/Simulink/BRAM_LT_Based/BRAM32bit/vivado/sysgen_STN/sysgen_STN.gen/sources_1/ip/bram_stn_32bit_0/bram_stn_32bit_mult_gen_v12_0_i0/bram_stn_32bit_mult_gen_v12_0_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bram_stn_32bit_mult_gen_v12_0_i0 || ORIG_REF_NAME==bram_stn_32bit_mult_gen_v12_0_i0} -quiet] -quiet

# XDC: e:/FPGAProject/01102022/FPGAResearch/5_Final_Submission/Simulink/BRAM_LT_Based/BRAM32bit/vivado/sysgen_STN/sysgen_STN.gen/sources_1/ip/bram_stn_32bit_0/constrs/bram_stn_32bit.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_stn_32bit_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
